import javax.swing.*;
import java.util.List;

/**
 *
 * @author AdekObiadek
 *
 */
public class GUIListaObiektow extends javax.swing.JFrame {
    public List < ObiektSportowy > obiektSportowyList;
    public ObiektSportowy obiektSportowy;

    /**
     * Creates new form GUI
     */
    public GUIListaObiektow() {
        initComponents();
    }

    public GUIListaObiektow(List < ObiektSportowy > obiektSportowyList) {
        this.obiektSportowyList = obiektSportowyList;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButtonExit = new javax.swing.JButton();
        jLabelPlacowka = new javax.swing.JLabel();
        jButtonManagerowie = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListObiektySportowe = new javax.swing.JList < ObiektSportowy > ();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        setTitle("Lista obiektów");

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabelPlacowka.setText("Wybierz placówke");

        jButtonManagerowie.setText("Managerowie");
        jButtonManagerowie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagerowieActionPerformed(evt);
            }
        });



        jListObiektySportowe.setModel(new javax.swing.AbstractListModel < ObiektSportowy > () {
            List list = obiektSportowyList;
            public int getSize() {
                return list.size();
            }
            public ObiektSportowy getElementAt(int i) {
                return (ObiektSportowy) list.get(i);
            }
        });
        jScrollPane1.setViewportView(jListObiektySportowe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelPlacowka)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane1)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                                                .addComponent(jButtonManagerowie)))
                                                .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabelPlacowka)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonExit)
                                        .addComponent(jButtonManagerowie))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    } // </editor-fold>

    private void jButtonManagerowieActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(jListObiektySportowe.getSelectedValue() != null) {
            new GUIListaManagerow(jListObiektySportowe.getSelectedValue()).setVisible(true);
        }else{
            new GUIError().setVisible(true);
        }
    }

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }


    // Variables declaration - do not modify
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonManagerowie;
    private javax.swing.JLabel jLabelPlacowka;
    private JList < ObiektSportowy > jListObiektySportowe;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration
}